Repository datatlas-erasme/front, pull requests merged in 2022-08, with the labels that each got.

#115 Introduce eslint no-console rule
  package.json
  src/components/buttons/button-type/button-default/ButtonDefault.tsx
  src/components/filters-desktop/desktop-panel/DesktopPanelControl.js
  src/components/map/Map.js
  src/components/modal/Modal.tsx
  src/hooks/useInstanceConfiguration.ts
  src/serviceWorker.js
Labels: refactoring, quality

#120 Updated docker-compose env mapping
  docker-compose.yml
  env.example
Labels: quality

#131 fix: copy webpack config override file in builder image
  Dockerfile
Labels: bug
